package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"jobportal-graphql/graph/model"
)

// CreateSignup is the resolver for the createSignup field.
func (r *mutationResolver) CreateSignup(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Svc.UserSignup(input)
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.NewCompany) (*model.Company, error) {
	return r.Svc.CreateCompany(input)
}
func (r *mutationResolver) ViewAllCompanies(ctx context.Context, input model.NewCompany) ([]*model.Company, error) {
	return r.Svc.ViewAllCompanies( )
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
